version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: PackageTracking.API/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PackageTrackingDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"